[tool.poetry]
name = "library-management"
version = "0.1.0"
description = ""
authors = ["Saugat Pachhai <suagatchhetri@outlook.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
